"""empty message

Revision ID: 280ee7323073
Revises: 8bac06eb9312
Create Date: 2023-05-06 11:09:54.423774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280ee7323073'
down_revision = '8bac06eb9312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('goal', 'goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('goal', 'title')
    op.drop_column('goal', 'id')
    # ### end Alembic commands ###
