"""fixed one to many relationship between author and book models

Revision ID: 42584462372e
Revises: afabcead0211
Create Date: 2021-11-03 03:55:45.989095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42584462372e'
down_revision = 'afabcead0211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
