"""empty message

Revision ID: 43de7462ba6d
Revises: 5a71960b7593
Create Date: 2021-11-01 09:05:02.695679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43de7462ba6d'
down_revision = '5a71960b7593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('goal', sa.Column('title', sa.String(length=250), nullable=True))
    op.drop_column('goal', 'goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('goal', 'title')
    op.drop_column('goal', 'id')
    # ### end Alembic commands ###
