"""empty message

Revision ID: 603b6509b8bf
Revises: b78ca3963b23
Create Date: 2022-11-07 18:07:00.972154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603b6509b8bf'
down_revision = 'b78ca3963b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'goal_title')
    # ### end Alembic commands ###
