"""empty message

Revision ID: 795dd0861e0d
Revises: 36ef713bcadb
Create Date: 2022-11-12 23:13:59.208095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795dd0861e0d'
down_revision = '36ef713bcadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
