"""changed is_complete type to bool, added completed_at

Revision ID: 7fa78e2b9ff2
Revises: 98d0ac9fc58d
Create Date: 2022-11-05 18:40:14.524228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa78e2b9ff2'
down_revision = '98d0ac9fc58d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
