"""Adds title to Goal and autoincrements goal_id

Revision ID: 812384d5a677
Revises: 4efe99052fda
Create Date: 2022-11-09 10:10:39.091323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812384d5a677'
down_revision = '4efe99052fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
