"""Revert changes to Task model

Revision ID: 8607dc03f9f9
Revises: 457a80026c3f
Create Date: 2024-11-05 19:24:17.030192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8607dc03f9f9'
down_revision = '457a80026c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('completed_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
