"""empty message

Revision ID: 87328eea7454
Revises: a7f25844d10b
Create Date: 2023-05-17 20:09:55.464105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87328eea7454'
down_revision = 'a7f25844d10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    op.drop_table('goal')
    # ### end Alembic commands ###
