"""empty message

Revision ID: 989dd296d4e6
Revises: 84dd54ffb7dc
Create Date: 2022-05-06 22:39:41.367325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989dd296d4e6'
down_revision = '84dd54ffb7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
